
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aiotg10
    username: root
    password: 111111

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.aiotg10.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-result-set-type: default